import no_image from "@/assets/main/img/no_image.jpg";

export const boardContent ={
    board_number: 15,
    content: [
        {
            text: ["01.", "LLM", "Review-Response"],
            title: "Project",
            content: "LangChain, RAG, Review",
            link: "/application/raam/",
            img: no_image,
            exBoard_title: ["Developing AI Assistant Model Framework", "For Review Management: Using LangChain and LLM"],
            exBoard_Content: " 해당프로젝트는 다양한 LLM과 LangChain 및 RAG를 이용하여 시장에서의 요구를 효과적으로 해결하고자 고안된 프로젝트입니다. 특히 호텔 산업 분야의 리뷰를 대상으로 진행되었으며, LLM을 활용한 특성 추출과정, 특성을 활용한 효과적인 참조과정(RAG), 특성을 활용한 프롬프트 엔지니어링 과정, 사용자의 피드백에 의한 데이터 저장과정 등을 내포하고 있습니다. \n\n 결과적으로 본 프로젝트는 리뷰 매니저를 대상으로하여 실증적인 도움을 주는 것에 강력한 주안점을 두고 있으며, 이를 증명하기 위한 다양한 평가를 진행하였습니다.",
            exBoard_Period: "2023. 08 ~ 2024. 03",
        },
        {
            text: ["02.", "title1", "title2"],
            title: "02",
            content: "temp2",
            link: "/application/2",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },
        {
            text: ["03.", "title1", "title2"],
            title: "03",
            content: "temp3",
            link: "/application/3",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["04.", "title1", "title2"],
            title: "04",
            content: "temp4",
            link: "/application/4",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["05.", "title1", "title2"],
            title: "05",
            content: "temp5",
            link: "/application/5",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["06.", "title1", "title2"],
            title: "06",
            content: "temp6",
            link: "/application/6",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["07.", "title1", "title2"],
            title: "07",
            content: "temp7",
            link: "/application/7",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["08.", "title1", "title2"],
            title: "08",
            content: "temp8",
            link: "/application/8",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["09.", "title1", "title2"],
            title: "09",
            content: "temp09",
            link: "/application/9",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["10.", "title1", "title2"],
            title: "10",
            content: "temp10",
            link: "/application/10",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["11.", "title1", "title2"],
            title: "11",
            content: "temp11",
            link: "/application/11",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["num", "title1", "title2"],
            title: "12",
            content: "temp12",
            link: "/application/12",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["num", "title1", "title2"],
            title: "13",
            content: "temp13",
            link: "/application/13",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["num", "title1", "title2"],
            title: "14",
            content: "temp14",
            link: "/application/14",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },            
        {
            text: ["num", "title1", "title2"],
            title: "15",
            content: "temp15",
            link: "/application/15",
            img: no_image,
            exBoard_title: ["title_1", "title_2"],
            exBoard_Content: "필요한 Content를 모두 채우세요.",
            exBoard_Period: "2023. 11",
        },
    ],
}