# Generated by Django 4.2.7 on 2023-11-28 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='file_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='fine_tune_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='fine_tuned_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responsemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='is_fine_tuned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_datas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='will_be_fine_tuned',
            field=models.BooleanField(default=False),
        ),
    ]
