# Generated by Django 4.2.7 on 2023-12-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raam', '0002_responsemodel_file_id_responsemodel_fine_tune_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_model', models.CharField(choices=[('gpt40_tb', 'OepnAI: GPT-4 turbo'), ('gpt35_tb', 'OpenAI: GPT-3.5 turbo'), ('llama2_7b', 'META: LLAMA-2 7B'), ('llama2_13b', 'META: LLAMA-2 13B'), ('palm2', 'Google: PaLM2'), ('phi15', 'Microsoft: PHI-1.5')], max_length=100)),
                ('user_review', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='fine_tuned_model',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResponseModel',
        ),
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
