# Generated by Django 4.2.7 on 2023-12-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raam', '0003_basicresponsemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicresponsemodel',
            old_name='user_review',
            new_name='inputText',
        ),
        migrations.RenameField(
            model_name='basicresponsemodel',
            old_name='base_model',
            new_name='model',
        ),
    ]
